name: Request to add a new resource
description: Use this issue to request to add a new resource to Calitp.org
title: "New resource request"
labels:
  - content
  - resources
body:
  - type: dropdown
    id: approval
    validations:
      required: true
    attributes:
      label: Approved?
      description: Has your content (document and headline) been approved been approved for publication? If not, please confirm approval in [#comms-and-content](https://cal-itp.slack.com/archives/C01LVK0C4NS).
      options:
        - "No"
        - "Yes"
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: Is the document correctly named and formatted?
      description: Ensure each of the following requirements are met for your file.
      options:
        - label: Did you start the filename with `Cal-ITP`?
          required: true
        - label: Did you remove all spaces between words in the filename? The only acceptable characters in the filename are letters, numbers, `-`, `.` and `_`.
          required: true
        - label: Did you ensure there are no revision dates or numbers in the filename? Limit usage of revision numbers or dates unless commonly understood and expected by the audience. Avoid `report-june-2024.pdf`, `file-v1.2.pdf`. Allowed `GTFS-guidlines-v3.pdf`, as version 3 is an official version number.
          required: true
        - label: Did you run this PDF through Adobe Acrobat's Accessibility Checker, and ensure the PDF passes all accessibility checks? Please review [this checklist](https://docs.google.com/document/d/1CkXfHDuJ4fR2wikGrsgyt4Dib6YdY3AhFmYtsk4kQXg/edit#heading=h.ecbzu7qezn59) to get more information on accessibility and how to run accessibility checks.
          required: true
  - type: dropdown
    attributes:
      label: Date - Year
      description: What year did this resource get published?
      multiple: false
      options:
        - 2025
        - 2024
        - 2023
        - 2022
        - 2021
        - 2020
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Date - Month
      description: What month did this resource get published?
      multiple: false
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: The title is used in list views on the home page and [https://calitp.org/resources](https://calitp.org/resources)
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Asset URL
      description: The URL of the resource
      placeholder: ex. link to a PDF from Google Drive
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Category
      description: What category is this resource in?
      multiple: false
      options:
        - Case studies
        - Fact sheets & overviews
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tag
      description: What tag is this resource in? (You may select more than one.)
      multiple: true
      options:
        - Contactless Payments
        - Benefits
        - GTFS
    validations:
      required: true
